#!/usr/bin/env python3
"""Generate the GitHub Pages appendix from the artifacts/ directory.

Run from the repository root:

    python3 generate.py

Reads everything under ``artifacts/`` and writes the derived pages into
``pages/``. Jekyll then only applies the layout and navigation.

Nothing is copied. The Pages source is the repository root, so ``artifacts/``
is inside the Jekyll source tree and is published in place; this script only
resolves artifact paths to URLs (see ``Artifacts``).

The source files under ``artifacts/`` are never modified, and none of them is
inlined into a page: every page shows the images and links the files, so the
artifacts stay the single source of truth and the pages stay short.

Standard library only, so it runs anywhere Python 3.8+ is available.
"""

from __future__ import annotations

import csv
import html
import re
import struct
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple, TypedDict

REPO = Path(__file__).resolve().parent
ARTIFACTS = REPO / "artifacts"
PAGES = REPO / "pages"

#: The whole-folder download offered on the Feature Model page. It lives inside
#: the folder it archives, so the bundler skips it when collecting members.
BUNDLE_NAME = "feature_model.zip"

#: Marks a generated page. ``prune_pages`` matches on the "GENERATED by"
#: prefix rather than the whole string, so renaming this script cannot leave
#: undeletable orphans behind.
BANNER = "<!-- GENERATED by generate.py — do not edit by hand. -->"
BANNER_MARK = "GENERATED by"

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

#: Tools in the order the paper presents them (Table "Sources and Tools
#: Selected for evaluation"), not alphabetically.
TOOLS: List[str] = [
    "mono2micro",
    "mono2micro_IBM",
    "Micro2Micro",
    "CARGO",
    "HyDec",
    "MEM",
    "MOSAIC",
]

#: Display names, since directory names are not presentable as-is.
TOOL_LABEL: Dict[str, str] = {
    "mono2micro": "Mono2Micro",
    "mono2micro_IBM": "Mono2Micro (IBM)",
    "Micro2Micro": "Micro2Micro",
    "CARGO": "CARGO",
    "HyDec": "HyDec",
    "MEM": "MEM",
    "MOSAIC": "MOSAIC",
}

#: exportedImages/ uses different casing from analyses/ for some tools.
IMAGE_PREFIX: Dict[str, str] = {
    "mono2micro": "mono2micro",
    "mono2micro_IBM": "mono2micro_IBM",
    "Micro2Micro": "micro2micro",
    "CARGO": "CARGO",
    "HyDec": "HyDec",
    "MEM": "MEM",
    "MOSAIC": "MOSAIC",
}

#: Which skill produced each mapping, and the tool's source paper.
TOOL_META: Dict[str, Dict[str, str]] = {
    "mono2micro": {
        "skill": "codebase-map",
        "source": "Lopes2023",
        "repo": "https://github.com/socialsoftware/mono2micro",
    },
    "mono2micro_IBM": {
        "skill": "docs-map",
        "source": "Wang2024",
        "repo": "https://www.ibm.com/products/mono2micro",
    },
    "Micro2Micro": {
        "skill": "codebase-map",
        "source": "Zhong2025",
        "repo": "https://github.com/wuxiaoxue/micro2micro",
    },
    "CARGO": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/konveyor/tackle-data-gravity-insights",
    },
    "HyDec": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/khaledsellami/decomp-hydec",
    },
    "MEM": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/gmazlami/microserviceExtraction-backend",
    },
    "MOSAIC": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/mosaic-tool/mosaic",
    },
}

#: Tools the paper lists but excludes from the mapping.
EXCLUDED_TOOLS: List[Tuple[str, str, str]] = [
    ("Data-Centric", "Wang2024", "No online codebase or documentation"),
    ("Log2MS", "Wang2024", "No online codebase or documentation"),
]

#: Source papers, in the order the Evaluation sub-navigation lists them. Which
#: tools belong to each is derived from TOOL_META["source"], never duplicated
#: here. ``union`` names the merged profile covering that paper's tools, where
#: one exists -- only Wang2024 has one, since the other two papers contribute a
#: single tool each and a union of one is just the tool.
PAPERS: List[Dict[str, str]] = [
    {"key": "Lopes2023", "slug": "lopes2023", "label": "Lopes 2023",
     "venue": "MSc thesis, Instituto Superior Técnico, 2023", "union": ""},
    {"key": "Wang2024", "slug": "wang2024", "label": "Wang 2024",
     "venue": "Empirical study comparing eight tools, 2024", "union": "wang"},
    {"key": "Zhong2025", "slug": "zhong2025", "label": "Zhong 2025",
     "venue": "IEEE Transactions on Software Engineering, 2025", "union": ""},
]

#: Where the repository is browsable. SKILL.md carries a YAML header, so Jekyll
#: renders it to SKILL.html and never emits a raw .md -- the only way to offer
#: the file itself is to link the source. See the include: note in _config.yml.
RAW_BASE = ("https://raw.githubusercontent.com/socialsoftware/"
            "UnifiedFeatureModelArtifacts/main")

#: Skills in pipeline order rather than alphabetical: what runs first reads
#: first. ``refresh-feature-model-infos`` is orthogonal and comes last.
SKILL_ORDER: List[str] = [
    "extract-codebases-from-paper",
    "codebase-map",
    "docs-map",
    "verify-analysis",
    "merge-profiles",
    "refresh-feature-model-infos",
]

#: Merged profiles: site key -> (profile stem, exportedImages prefix, label).
MERGED: List[Tuple[str, str, str]] = [
    ("all-tools", "all_tools", "All tools"),
    ("wang", "wang", "Wang et al. tools"),
    ("mono2micro+Micro2Micro", "mono2micro+micro2micro", "Mono2Micro + Micro2Micro"),
]

#: Colour semantics, per the paper's Table "Meaning of colors in the mapping".
#: Order is the reporting order of Table "Summary of the mapping results".
COLOURS: List[str] = [
    "Dark_Green",
    "Light_Green",
    "Yellow",
    "Red",
    "Orange",
    "Magenta",
]

COLOUR_MEANING: Dict[str, str] = {
    "Dark_Green": "Every feature in the group was mapped to the tool "
                  "(feature groups only, never leaves)",
    "Light_Green": "The feature was mapped to the tool",
    "Yellow": "The feature was not mapped to the tool, but it is optional",
    "Red": "The feature was not mapped to the tool, although it was mandatory",
    "Orange": "The feature was not mapped to the tool and this violates a constraint",
    "Magenta": "The mapping of this feature is inconclusive (automated mapping), "
               "or the feature is present in the tool but absent from the model",
}

COLOUR_SHORT: Dict[str, str] = {
    "Dark_Green": "Group fully mapped",
    "Light_Green": "Mapped",
    "Yellow": "Unmapped (optional)",
    "Red": "Unmapped (mandatory)",
    "Orange": "Constraint violation",
    "Magenta": "Inconclusive / extra",
}


#: Reader-facing summaries of each skill. The ``description`` in SKILL.md is a
#: trigger-phrase prompt aimed at the model ("use this when the user says ...")
#: and refers to an earlier repository layout, so it does not read as prose on a
#: web page. The raw description stays available on the SKILL.md itself.
SKILL_SUMMARY: Dict[str, str] = {
    "extract-codebases-from-paper":
        "Given a paper, identifies the tools it discusses and, for each one, "
        "searches for its codebase or documentation URL. Codebases found are "
        "downloaded automatically; missing ones are recorded for a manual "
        "lookup. Particularly useful for papers that compare several tools, and "
        "it copes with broken or outdated links by falling back to a web search.",
    "codebase-map":
        "Given the codebase of a tool, maps it onto the feature model and "
        "produces three artifacts: a human-readable report, an analysis "
        "document, and a colour profile. The analysis mirrors the structure of "
        "the feature model, one bullet per leaf feature, and every finding must "
        "cite at least one <code>file:line</code> reference so the mapping can "
        "be verified independently.",
    "docs-map":
        "Mirrors <code>codebase-map</code> for tools that are not open source. "
        "It takes a documentation URL instead of a local path and cites "
        "documentation links rather than <code>file:line</code> references as "
        "evidence, producing the same three artifacts.",
    "verify-analysis":
        "Reconciles several runs of the mapping skills, which are "
        "non-deterministic and may differ in results, evidence, and conclusions. "
        "It inspects the different versions of a tool's mapping and, where they "
        "disagree, re-examines the evidence to determine the best-supported "
        "conclusion. When that is still inconclusive the feature is marked "
        "inconclusive and left for the user to decide.",
    "merge-profiles":
        "Combines the per-tool colour profiles into a union profile showing what "
        "a chosen set of tools covers together. With no arguments it merges "
        "every analysed tool; given a paper it merges only that paper's tools; "
        "given tool names it merges just those.",
    "refresh-feature-model-infos":
        "Checks whether the files that depend on the feature model are still in "
        "sync with it, reports any discrepancies, and updates them once "
        "approved.",
}


#: One line per downloadable mapping, for the Colour profiles table. Keyed by
#: tool name and by MERGED key. TOOL_META carries only provenance (skill,
#: source, repo), so there is nowhere else to say what a tool actually does;
#: this mirrors SKILL_SUMMARY above. The merged entries say what the union
#: means, since a reader meets "wang" here as a filename and nothing else.
MAPPING_BLURB: Dict[str, str] = {
    "mono2micro": "Identifies microservices in a monolith from the codebase "
                  "and its execution traces. The tool the initial model was "
                  "derived from.",
    "mono2micro_IBM": "IBM's commercial offering of the same name, mapped from "
                      "its documentation rather than its source.",
    "Micro2Micro": "Refactors an existing microservice architecture rather "
                   "than splitting a monolith, moving functionality between "
                   "services.",
    "CARGO": "Partitions a monolith using a graph of its code and data "
             "dependencies, with the database kept in view.",
    "HyDec": "Decomposes a monolith with a hybrid of static and dynamic "
             "analysis.",
    "MEM": "Derives candidate microservices from version-control history, "
           "grouping code that tends to change together.",
    "MOSAIC": "Identifies microservices from a combination of structural and "
              "semantic signals in the codebase.",
    "all-tools": "Every one of the seven mapped tools merged into one profile: "
                 "what they cover together, and what none of them covers.",
    "wang": "The tools evaluated in Wang 2024, merged into one profile.",
    "mono2micro+Micro2Micro": "The two tools that share a lineage, merged into "
                              "one profile. Discussed in the paper as a pair; "
                              "it has no page of its own.",
}


class BuildError(RuntimeError):
    """A required input is missing or malformed."""


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------

def read(path: Path) -> str:
    if not path.is_file():
        raise BuildError(f"missing required file: {path.relative_to(REPO)}")
    return path.read_text(encoding="utf-8")


def human_size(nbytes: int) -> str:
    if nbytes < 1024:
        return f"{nbytes} B"
    if nbytes < 1024 * 1024:
        return f"{nbytes / 1024:.0f} KB"
    return f"{nbytes / (1024 * 1024):.1f} MB"


def png_size(path: Path) -> Tuple[int, int]:
    """Read width/height straight from the PNG IHDR chunk."""
    with path.open("rb") as fh:
        head = fh.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        raise BuildError(f"not a PNG: {path}")
    return struct.unpack(">II", head[16:24])


def slug(text: str) -> str:
    """Approximate kramdown's heading -> anchor conversion."""
    out = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_]+", "-", out).strip("-")


def chip(colour: Optional[str]) -> str:
    if not colour:
        return '<span class="chip chip-none">not in model</span>'
    cls = colour.lower()
    return f'<span class="chip chip-{cls}">{html.escape(COLOUR_SHORT.get(colour, colour))}</span>'


def write_page(rel: str, front: Dict[str, object], body: str) -> Path:
    """Write a generated page with YAML frontmatter."""
    dest = PAGES / rel
    dest.parent.mkdir(parents=True, exist_ok=True)

    lines = ["---"]
    for key, value in front.items():
        if value is None:
            continue
        if isinstance(value, (int, float)):
            lines.append(f"{key}: {value}")
        else:
            lines.append(f'{key}: "{str(value)}"')
    lines.append("---")
    lines.append(BANNER)
    lines.append("")

    dest.write_text("\n".join(lines) + body.rstrip() + "\n", encoding="utf-8")
    return dest


# --------------------------------------------------------------------------
# Artifacts
# --------------------------------------------------------------------------

class Artifacts:
    """Maps logical asset keys to the real files under ``artifacts/``.

    Nothing is copied. The Pages source is the repository root, so Jekyll
    publishes ``artifacts/`` in place and the site links straight into it; this
    class only records where each artifact lives and turns that into a URL.

    ``paths`` doubles as the existence registry the page renderers query
    (``if key not in artifacts: ...``) to decide whether an optional artifact
    was shipped.
    """

    def __init__(self) -> None:
        self.paths: Dict[str, Path] = {}

    def register(self, src: Path, key: str, *, required: bool = True) -> Optional[str]:
        """Record a logical key for a real artifact file.

        Returns the key, or None when an optional file is absent. Raises for a
        missing required file, matching the old copy() contract.
        """
        if not src.is_file():
            if required:
                raise BuildError(f"missing artifact: {src.relative_to(REPO)}")
            return None
        self.paths[key] = src
        return key

    def __contains__(self, key: str) -> bool:
        return key in self.paths

    def path(self, key: str) -> Path:
        """The real artifact path, for png_size() and the CSV read."""
        try:
            return self.paths[key]
        except KeyError:
            raise BuildError(f"unregistered artifact key: {key}") from None

    def size(self, key: str) -> str:
        return human_size(self.paths[key].stat().st_size) if key in self.paths else ""

    def url(self, key: str) -> str:
        """Site URL of the artifact, addressed in place under artifacts/.

        Spaces are percent-encoded here rather than left to Liquid's
        ``relative_url``. That filter would encode them correctly, but the
        {{BASE}} placeholder never survives long enough to reach it: the
        substitution in apply_baseurl matches a run of non-whitespace, so a
        raw space truncates the URL mid-path. The meta-review CSV and PDF are
        the files this affects.

        Only the space is encoded, so the result stays readable and
        Addressable's later normalise() is a no-op rather than a double-encode.
        """
        rel = self.path(key).relative_to(REPO).as_posix()
        return "{{BASE}}/" + rel.replace(" ", "%20")


def build_feature_model_bundle() -> Path:
    """Zip the whole feature_model/ folder and return the archive path.

    Everything else on the site is linked in place (see ``Artifacts``), but a
    "download the folder" link needs a real file, so this is the one artifact
    the script creates rather than merely locating.

    That makes it a committed binary: GitHub Pages builds the committed tree and
    never runs this script, so re-run generate.py and commit the result after
    changing anything under artifacts/feature_model/, or the bundle silently
    serves stale profiles.

    Written deterministically -- sorted members, fixed timestamps and modes --
    so an unchanged folder yields a byte-identical archive. Otherwise checkout
    mtimes would leak into the zip and every build would show a spurious diff on
    a 70 KB binary.
    """
    src = ARTIFACTS / "feature_model"
    if not src.is_dir():
        raise BuildError(f"missing {src.relative_to(REPO)}/")

    # .project is FeatureIDE's Eclipse metadata: it names a local workspace
    # project and means nothing outside it, so it stays out of the download.
    members = sorted(
        (p for p in src.rglob("*")
         if p.is_file() and p.name not in (BUNDLE_NAME, ".project")),
        key=lambda p: p.relative_to(src).as_posix())
    if not members:
        raise BuildError(f"nothing to bundle under {src.relative_to(REPO)}/")

    out = src / BUNDLE_NAME
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in members:
            # Rooted at feature_model/ so unzipping yields the folder, not a
            # scatter of loose files in the reader's download directory.
            info = zipfile.ZipInfo(
                "feature_model/" + path.relative_to(src).as_posix(),
                date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, path.read_bytes())
    return out


class BuildSummary(TypedDict):
    """What register_artifacts reports back to main() for the closing print.

    Spelled out rather than Dict[str, object] so ``extended_models`` stays a
    list of names: as ``object`` it cannot be passed to str.join().
    """
    images: int
    profiles: int
    extended_models: List[str]
    has_pdf: bool


def register_artifacts(artifacts: Artifacts) -> BuildSummary:
    """Register every artifact the site links to. Returns a small summary."""
    # Only the count is ever reported, and every registration below is required
    # -- register() either returns the key or raises -- so counting avoids
    # collecting an Optional[str] into a List[str].
    images = 0

    exported = ARTIFACTS / "evaluation" / "exportedImages"
    if not exported.is_dir():
        raise BuildError("missing artifacts/evaluation/exportedImages/")
    for png in sorted(exported.glob("*.png")):
        artifacts.register(png, f"images/{png.name}")
        images += 1

    # The two rendered feature models.
    artifacts.register(
        ARTIFACTS / "feature_model" / "extended.png", "images/feature_model.png")
    artifacts.register(
        ARTIFACTS / "initialFeatureModelFromMono2Micro" / "initial_extended.png",
        "images/initial_feature_model.png")
    images += 2

    # Colour profiles. A dotfolder, so it only reaches the built site because
    # _config.yml lists `.profiles` under `include:`.
    profiles = ARTIFACTS / "feature_model" / ".profiles"
    profile_files = sorted(profiles.glob("*.profile"))
    if not profile_files:
        raise BuildError("no .profile files found")
    for prof in profile_files:
        artifacts.register(prof, f"profiles/{prof.name}")

    # Built, not located -- and built here, once the profiles above are known
    # to exist, so the download can never ship a folder missing them.
    artifacts.register(build_feature_model_bundle(), "bundles/feature_model.zip")

    # FeatureIDE models: the canonical one, the initial one, and the
    # tool-specific extended ones.
    artifacts.register(ARTIFACTS / "feature_model" / "feature_model.xml",
                       "models/feature_model.xml")
    artifacts.register(ARTIFACTS / "initialFeatureModelFromMono2Micro" / "model.xml",
                       "models/initial_feature_model.xml")

    extended_models: List[str] = []
    eval_models = ARTIFACTS / "evaluation" / "feature_models"
    if eval_models.is_dir():
        for sub in sorted(eval_models.iterdir()):
            xml = sub / "feature_model.xml"
            if xml.is_file():
                artifacts.register(xml, f"models/{sub.name}_feature_model.xml")
                extended_models.append(sub.name)

    # Meta-review. The source filenames contain spaces; they are served as-is
    # and percent-encoded by Liquid's relative_url (see Artifacts.url).
    meta_dir = ARTIFACTS / "meta-review"
    csv_src = next(meta_dir.glob("*.csv"), None)
    pdf_src = next(meta_dir.glob("*.pdf"), None)
    if csv_src is None:
        raise BuildError("missing meta-review CSV")
    artifacts.register(csv_src, "data/meta-review.csv")
    if pdf_src is not None:
        artifacts.register(pdf_src, "data/meta-review.pdf")

    # The FeatureIDE configuration beside the canonical model. Optional: it is
    # a selected product rather than the model itself.
    artifacts.register(ARTIFACTS / "feature_model" / "configs" / "default.xml",
                       "models/feature_model_config.xml", required=False)

    # Per-tool analyses and run notes, so each page can offer the raw markdown.
    # Neither file carries a YAML header, so Jekyll copies them verbatim and
    # they are downloadable as-is -- unlike SKILL.md, which it renders.
    for tool in TOOLS:
        base = ARTIFACTS / "evaluation" / "analyses" / tool
        artifacts.register(base / "analysis.md", f"analyses/{tool}-analysis.md")
        artifacts.register(base / "README.md", f"analyses/{tool}-readme.md",
                           required=False)

    return {
        "images": images,
        "profiles": len(profile_files),
        "extended_models": extended_models,
        "has_pdf": pdf_src is not None,
    }


# --------------------------------------------------------------------------
# Parsers
# --------------------------------------------------------------------------

def parse_profile(path: Path) -> Dict[str, str]:
    """Parse a FeatureIDE ``.profile`` into ``{feature: Colour}``.

    Line 1 is the "is default profile" flag; the trailing
    ``featureColorMeaning*`` entries are the legend, not features.
    """
    colours: Dict[str, str] = {}
    for line in read(path).splitlines()[1:]:
        line = line.strip()
        if not line or "=" not in line:
            continue
        name, _, value = line.partition("=")
        if name.startswith("featureColorMeaning"):
            continue
        colours[name.strip()] = value.strip()
    if not colours:
        raise BuildError(f"no feature colours in {path.name}")
    return colours


class Node:
    """One node of the feature-model tree."""

    __slots__ = ("name", "kind", "mandatory", "abstract", "depth", "children")

    def __init__(self, name: str, kind: str, mandatory: bool,
                 abstract: bool, depth: int) -> None:
        self.name = name
        self.kind = kind              # and | or | alt | feature
        self.mandatory = mandatory
        self.abstract = abstract
        self.depth = depth
        self.children: List["Node"] = []

    def walk(self) -> Iterable["Node"]:
        yield self
        for child in self.children:
            yield from child.walk()


def parse_feature_model(path: Path) -> Tuple[Node, List[str]]:
    """Parse FeatureIDE XML into a tree plus readable constraint strings."""
    root_el = ET.fromstring(read(path))

    struct = root_el.find("struct")
    if struct is None or len(struct) == 0:
        raise BuildError(f"no <struct> in {path.name}")

    def build(el: ET.Element, depth: int) -> Node:
        node = Node(
            name=el.get("name", "?"),
            kind=el.tag,
            mandatory=el.get("mandatory") == "true",
            abstract=el.get("abstract") == "true",
            depth=depth,
        )
        for child in el:
            if child.tag in ("and", "or", "alt", "feature"):
                node.children.append(build(child, depth + 1))
        return node

    tree = build(struct[0], 0)

    def render(el: ET.Element) -> str:
        tag = el.tag
        if tag == "var":
            return (el.text or "").strip()
        parts = [render(c) for c in el]
        if tag == "imp":
            return f"{parts[0]} &rarr; {parts[1]}"
        if tag == "disj":
            return "(" + " &or; ".join(parts) + ")"
        if tag == "conj":
            return "(" + " &and; ".join(parts) + ")"
        if tag == "not":
            return f"&not;{parts[0]}"
        if tag == "eq":
            return f"{parts[0]} &harr; {parts[1]}"
        return " ".join(parts)

    constraints: List[str] = []
    for rule in root_el.findall("./constraints/rule"):
        for child in rule:
            if child.tag != "graphics":
                constraints.append(render(child))
                break

    return tree, constraints



def parse_skills() -> List[Dict[str, str]]:
    """Read name/description from each SKILL.md frontmatter."""
    skills_dir = ARTIFACTS / ".claude" / "skills"
    if not skills_dir.is_dir():
        raise BuildError("missing artifacts/.claude/skills/")

    out: List[Dict[str, str]] = []
    for sub in sorted(skills_dir.iterdir()):
        skill_md = sub / "SKILL.md"
        if not skill_md.is_file():
            continue
        text = read(skill_md)
        match = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        if not match:
            raise BuildError(f"no frontmatter in {skill_md}")
        front = match.group(1)

        def field(key: str) -> str:
            m = re.search(rf"^{key}:\s*(.+?)\s*$", front, re.M)
            return m.group(1).strip() if m else ""

        out.append({
            "name": field("name") or sub.name,
            "description": field("description"),
            "tools": field("allowed-tools"),
            "dir": sub.name,
        })
    if not out:
        raise BuildError("no skills found")
    return out


# --------------------------------------------------------------------------
# Rendering helpers
# --------------------------------------------------------------------------




def table(headers: Sequence[str], rows: Iterable[Sequence[str]],
          extra_class: str = "") -> str:
    """Render an HTML table inside a horizontal-scroll wrapper."""
    cls = f' class="{extra_class}"' if extra_class else ""
    parts = [f'<div class="table-scroll{cls and ""}">', f"<table{cls}>", "<thead><tr>"]
    parts += [f"<th>{h}</th>" for h in headers]
    parts += ["</tr></thead>", "<tbody>"]
    for row in rows:
        parts.append("<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>")
    parts += ["</tbody>", "</table>", "</div>"]
    return "\n".join(parts)


def figure(caption: str, shots: Sequence[Dict[str, str]]) -> str:
    """A lightbox figure. Each shot: {file, label, meta, alt}."""
    if not shots:
        return ""
    out = ['<figure class="fm-image">',
           f"<figcaption>{caption}</figcaption>",
           '<div class="fm-shots">']
    for shot in shots:
        out.append(
            '<button type="button" class="fm-shot"'
            f' data-full="{shot["file"]}"'
            f' data-title="{html.escape(shot["label"], quote=True)}"'
            f' data-alt="{html.escape(shot.get("alt", shot["label"]), quote=True)}">'
            f'<img src="{shot["file"]}" alt="{html.escape(shot.get("alt", shot["label"]))}" loading="lazy">'
            '<span class="fm-shot-label">'
            f'<b>{html.escape(shot["label"])}</b>'
            # meta carries an entity (the &times; between the pixel dimensions),
            # so it is already HTML and must not be escaped again.
            f'<span>{shot.get("meta", "")} · click to zoom</span>'
            "</span></button>"
        )
    out += ["</div>", "</figure>"]
    return "\n".join(out)


def colour_legend() -> str:
    items = ['<ul class="legend">']
    for colour in COLOURS:
        items.append(f"<li>{chip(colour)}<span>{html.escape(COLOUR_MEANING[colour])}</span></li>")
    items.append("</ul>")
    return "\n".join(items)


def downloads_block(assets: Artifacts, entries: Sequence[Tuple[str, str]],
                    heading: str = "## Downloads") -> str:
    """A downloads table: (asset-rel-path, description).

    ``heading`` is overridable because a page can carry more than one table --
    a tool page with a proposed model extension keeps that download under its
    own section rather than repeating "Downloads". Pass an empty string to omit
    the heading entirely.
    """
    rows = []
    for rel, description in entries:
        name = rel.rsplit("/", 1)[-1]
        rows.append((
            f'<a href="{assets.url(rel)}" download><code>{html.escape(name)}</code></a>',
            html.escape(description),
            assets.size(rel),
        ))
    prefix = f"\n{heading}\n\n" if heading else "\n"
    return (prefix
            + table(["File", "What it is", "Size"], rows, extra_class="downloads")
            + "\n")


def colour_counts(colours: Dict[str, str]) -> Dict[str, int]:
    counts = {c: 0 for c in COLOURS}
    for value in colours.values():
        if value in counts:
            counts[value] += 1
    return counts


# --------------------------------------------------------------------------
# Page renderers
# --------------------------------------------------------------------------

def tool_images(tool: str, assets: Artifacts) -> Dict[str, Dict[str, str]]:
    """The mapping images for one tool, keyed by family.

    Four families exist in exportedImages/, with different provenance, and the
    pages label them as such rather than presenting them as one set:

    ``claude``    the mapping a mapping skill produced, unedited;
    ``revised``   the same mapping after the authors checked the evidence;
    ``extended``  the model with this tool's missing features added -- a manual
                  proposal, not skill output, so pages show it separately;
    ``manual``    a hand-made reference mapping. Only mono2micro has one.
    """
    prefix = IMAGE_PREFIX[tool]
    wanted = [
        ("claude", f"{prefix}_claudeMapping.png", "Automated mapping"),
        ("revised", f"{prefix}_revisedMapping.png", "Revised mapping"),
        ("extended", f"{prefix}_extendedMapping.png", "Extended model"),
        ("manual", f"{prefix}_manualMapping.png", "Manual mapping"),
    ]
    return collect_images(assets, wanted, TOOL_LABEL[tool])


def collect_images(assets: Artifacts,
                   wanted: Sequence[Tuple[str, str, str]],
                   subject: str) -> Dict[str, Dict[str, str]]:
    """Resolve (family, filename, label) triples to lightbox shot dicts.

    Absent files are skipped, not an error: only three tools have an extended
    model and only one has a manual mapping.
    """
    shots: Dict[str, Dict[str, str]] = {}
    for family, filename, label in wanted:
        rel = f"images/{filename}"
        if rel not in assets:
            continue
        width, height = png_size(assets.path(rel))
        shots[family] = {
            "file": assets.url(rel),
            "label": label,
            "meta": f"{width}&times;{height}",
            "alt": f"{subject} {label.lower()} over the feature model",
            "rel": rel,
        }
    return shots


def sub_nav(active_paper: str = "", active_tool: str = "") -> str:
    """The two-level Evaluation navigation strip.

    Rendered as static HTML on every Evaluation page so each tool keeps its own
    URL and stays deep-linkable -- an artifact appendix gets cited by URL, so
    client-side tabs would make the interesting pages unaddressable.

    The second row appears only for the active paper, keeping the strip to a
    readable width.
    """
    rows: List[str] = ['<nav class="sub-nav" aria-label="Evaluation">']

    top: List[str] = ['<ul class="sub-nav-papers">']
    top.append(_sub_nav_item("All tools", "{{BASE}}/evaluation/all-tools/",
                             active_tool == "all-tools"))
    for paper in PAPERS:
        top.append(_sub_nav_item(
            paper["label"], "{{BASE}}/evaluation/" + paper["slug"] + "/",
            paper["key"] == active_paper))
    top.append("</ul>")
    rows.append("".join(top))

    if active_paper:
        paper = next(p for p in PAPERS if p["key"] == active_paper)
        siblings: List[str] = ['<ul class="sub-nav-tools">']
        if paper["union"]:
            siblings.append(_sub_nav_item(
                f"All {paper['label']} tools",
                "{{BASE}}/evaluation/" + paper["slug"] + "/all/",
                active_tool == paper["union"]))
        for tool in TOOLS:
            if TOOL_META[tool]["source"] != active_paper:
                continue
            siblings.append(_sub_nav_item(
                TOOL_LABEL[tool],
                "{{BASE}}/evaluation/" + paper["slug"] + "/" + tool.lower() + "/",
                tool == active_tool))
        siblings.append("</ul>")
        rows.append("".join(siblings))

    rows.append("</nav>")
    return "\n".join(rows) + "\n"


def _sub_nav_item(label: str, href: str, current: bool) -> str:
    mark = ' aria-current="page"' if current else ""
    return f'<li><a href="{href}"{mark}>{html.escape(label)}</a></li>'


def profile_downloads(assets: Artifacts, stem: str,
                      review_stem: str = "") -> List[Tuple[str, str]]:
    """Download entries for a profile pair, skipping whichever is absent.

    ``review_stem`` exists because one merged profile breaks the convention:
    the reviewed twin of ``mono2micro+Micro2Micro`` is filed under
    ``mono2micro_user_review+Micro2Micro_user_review``, not under the plain
    ``_user_review`` suffix every other pair uses.
    """
    entries: List[Tuple[str, str]] = []
    auto = f"profiles/{stem}.profile"
    if auto in assets:
        entries.append((auto, "Colour profile — automated mapping"))
    review = f"profiles/{review_stem or stem + '_user_review'}.profile"
    if review in assets:
        entries.append((review, "Colour profile — after the authors' review"))
    return entries


def mapping_figures(shots: Dict[str, Dict[str, str]], subject: str) -> List[str]:
    """The claude/revised pair plus any manual mapping, with provenance stated."""
    parts: List[str] = []
    pair = [shots[k] for k in ("claude", "revised") if k in shots]
    if pair:
        parts.append(figure(
            f"{subject} mapped onto the feature model. The automated mapping is "
            "the skill's own output; the revised one is the authors' correction "
            "of it after re-checking the cited evidence. Click to open full "
            "screen (drag to pan, scroll to zoom).",
            pair))
    if "manual" in shots:
        parts.append("\n### Manual reference mapping\n")
        parts.append(
            '<div class="note"><p>A mapping done by hand, before the skills '
            'existed. It is kept as a baseline for comparison and is not skill '
            'output.</p></div>\n')
        parts.append(figure("Hand-made reference mapping.", [shots["manual"]]))
    return parts


def render_feature_model(assets: Artifacts) -> None:
    """Tab 1: the proposed model -- the image, and the model itself."""
    tree, constraints = parse_feature_model(
        ARTIFACTS / "feature_model" / "feature_model.xml")
    nodes = list(tree.walk())
    groups = [n for n in nodes if n.children]
    leaves = [n for n in nodes if not n.children]
    width, height = png_size(assets.path("images/feature_model.png"))

    body = [
        "# The unified feature model\n",
        figure("The complete feature model, rendered from FeatureIDE.",
               [{"file": assets.url("images/feature_model.png"),
                 "label": "Unified feature model",
                 "meta": f"{width}&times;{height}",
                 "alt": "The complete unified feature model as a horizontal tree"}]),
    ]

    body.append("\n## Colour profiles\n")
    body.append(
        "Every colour profile available for download: one per tool, plus the "
        "merged profiles. \nEach is a FeatureIDE colour profile that paints the "
        "model with that tool's mapping. The <i>reviewed</i> column is the "
        "authors' revised version of the automated mapping.\n")

    rows = []
    for tool in TOOLS:
        paper = next(p for p in PAPERS if p["key"] == TOOL_META[tool]["source"])
        rows.append(_profile_row(
            assets, TOOL_LABEL[tool], tool,
            page=f"{{{{BASE}}}}/evaluation/{paper['slug']}/{tool.lower()}/"))
    for key, _prefix, label in MERGED:
        review = ("mono2micro_user_review+Micro2Micro_user_review"
                  if key == "mono2micro+Micro2Micro" else "")
        # mono2micro+Micro2Micro is deliberately pageless (see
        # render_union_page), so its row is plain text and the blurb carries it.
        page = ""
        if key == "all-tools":
            page = "{{BASE}}/evaluation/all-tools/"
        elif key == "wang":
            paper = next(p for p in PAPERS if p["union"] == key)
            page = f"{{{{BASE}}}}/evaluation/{paper['slug']}/all/"
        rows.append(_profile_row(assets, label, key, review, page=page))
    body.append(table(["Mapping", "What it is", "Automated", "Reviewed"], rows))

    entries = [
        ("bundles/feature_model.zip",
         "Everything below in one archive: the model, every colour profile, "
         "and the configuration"),
        ("models/feature_model.xml", "The feature model (FeatureIDE XML)"),
        ("images/feature_model.png", "The rendered model, as shown above"),
    ]
    if "models/feature_model_config.xml" in assets:
        entries.append(("models/feature_model_config.xml",
                        "FeatureIDE configuration listing every feature"))
    body.append(downloads_block(assets, entries,
                                heading="## Download Artifacts"))

    write_page("feature-model.md",
               {"layout": "default", "title": "Feature model",
                "nav_title": "Feature Model", "nav_order": 2,
                "permalink": "/feature-model/"},
               "\n".join(body))


def _profile_row(assets: Artifacts, label: str, stem: str,
                 review_stem: str = "",
                 page: str = "") -> Tuple[str, str, str, str]:
    """One row of the Colour profiles table.

    ``page`` is the mapping's own page, where it has one. It is optional
    because mono2micro+Micro2Micro deliberately has none, and that row then
    renders as plain text rather than a dead link.
    """
    def link(rel: str) -> str:
        if rel not in assets:
            return "—"
        name = rel.rsplit("/", 1)[-1]
        return f'<a href="{assets.url(rel)}" download><code>{html.escape(name)}</code></a>'

    name = html.escape(label)
    return (f'<a href="{page}">{name}</a>' if page else name,
            html.escape(MAPPING_BLURB.get(stem, "")),
            link(f"profiles/{stem}.profile"),
            link(f"profiles/{review_stem or stem + '_user_review'}.profile"))


def render_initial_model(assets: Artifacts) -> None:
    """Tab 2: the model that preceded generalisation."""
    tree, constraints = parse_feature_model(
        ARTIFACTS / "initialFeatureModelFromMono2Micro" / "model.xml")
    nodes = list(tree.walk())
    width, height = png_size(assets.path("images/initial_feature_model.png"))

    body = [
        "# The initial feature model\n",
        f"Before the generalisation, the model was derived top-down from a "
        f"single tool: Mono2Micro's identification pipeline. This initial "
        f"version has <b>{len(nodes)}</b> features and "
        f"<b>{len(constraints)}</b> cross-tree constraints, rooted at "
        f"<i>{html.escape(tree.name)}</i>. It is published so the two can be "
        f"compared — the difference is what the bottom-up phase, driven by the "
        f"meta-review and the tool mappings, actually added.\n",

        figure("The initial feature model, before the bottom-up generalisation.",
               [{"file": assets.url("images/initial_feature_model.png"),
                 "label": "Initial feature model",
                 "meta": f"{width}&times;{height}",
                 "alt": "The initial feature model derived from Mono2Micro"}]),
    ]

    entries = [
        ("models/initial_feature_model.xml",
         "The initial feature model (FeatureIDE XML)"),
        ("images/initial_feature_model.png", "The rendered model, as shown above"),
    ]
    body.append(downloads_block(assets, entries))

    write_page("initial-model.md",
               {"layout": "default", "title": "Initial model",
                "nav_title": "Initial Model", "nav_order": 3,
                "permalink": "/initial-model/"},
               "\n".join(body))


def render_meta_review(assets: Artifacts) -> int:
    """Tab 3: a short explanation and the two downloads.

    Returns the number of studies, read from the CSV so the count on the page
    cannot drift from the data.
    """
    csv_path = assets.path("data/meta-review.csv")
    with csv_path.open(encoding="utf-8-sig", newline="") as fh:
        records = list(csv.reader(fh))
    if len(records) < 6:
        raise BuildError("meta-review CSV has too few records")

    # Rows 1-4 are the nested header reproducing the model's dimensions, row 5
    # is a vocabulary row; the studies start after them.
    studies = [r[0].strip() for r in records[5:] if r and r[0].strip()]

    body = [
        "# Meta-review\n",
        f"A review of <b>{len(studies)}</b> secondary studies on monolith-to-"
        f"microservice decomposition. Each study is a row; the columns follow "
        f"the dimensions of the feature model, recording the concepts that study "
        f"reports for each one. This is the bottom-up evidence the model was "
        f"generalised from.\n",
        "<p>Studies reviewed: "
        + ", ".join(f"<i>{html.escape(s)}</i>" for s in studies)
        + ".</p>\n",
        '<div class="note"><p>The table is wide and deeply nested — four header '
        'rows — so it is published as data rather than rendered here. The CSV is '
        'the source; the PDF is the same table laid out for reading.</p></div>\n',
    ]

    entries = [("data/meta-review.csv", "The meta-review table (CSV)")]
    if "data/meta-review.pdf" in assets:
        entries.append(("data/meta-review.pdf", "The same table, as a PDF"))
    body.append(downloads_block(assets, entries))

    write_page("meta-review.md",
               {"layout": "default", "title": "Meta-review",
                "nav_title": "Meta-review", "nav_order": 4,
                "permalink": "/meta-review/"},
               "\n".join(body))
    return len(studies)


def render_skills(assets: Artifacts) -> int:
    """Tab 4: the six mapping skills, each downloadable."""
    skills = {s["dir"]: s for s in parse_skills()}
    missing = [d for d in SKILL_ORDER if d not in skills]
    if missing:
        raise BuildError(f"SKILL_ORDER names unknown skills: {missing}")
    extra = [d for d in skills if d not in SKILL_ORDER]

    body = [
        "# Mapping skills\n",
        "The six skills that produced the evaluation. They are Claude Code "
        "skills: each <code>SKILL.md</code> is a written procedure the model "
        "follows, so the mapping process is inspectable and re-runnable rather "
        "than a one-off prompt.\n",
        '<div class="note"><p>The skills are <b>non-deterministic</b>: running '
        'one twice can produce different verdicts. That is why '
        '<code>verify-analysis</code> exists, and why every mapping in the '
        'evaluation is published in both its automated and its reviewed '
        'form.</p></div>\n',
        "\n## The pipeline\n",
        '<pre class="pipeline">'
        "extract-codebases-from-paper   paper  -> tools + codebases\n"
        "         |\n"
        "         v\n"
        "codebase-map / docs-map        tool   -> analysis + colour profile\n"
        "         |\n"
        "         v\n"
        "verify-analysis                reconciles repeated runs\n"
        "         |\n"
        "         v\n"
        "merge-profiles                 per-tool profiles -> union profile"
        "</pre>\n",
        "<p><code>refresh-feature-model-infos</code> sits outside this chain: it "
        "runs whenever the feature model changes, to keep the files that "
        "describe it in step.</p>\n",
        "\n## The skills\n",
        '<ul class="cards skill-cards">',
    ]

    for name in SKILL_ORDER + extra:
        skill = skills[name]
        summary = SKILL_SUMMARY.get(name)
        if summary is None:
            # Fall back to the frontmatter description, which is written as a
            # trigger phrase for the model rather than as prose, but is better
            # than an empty card.
            summary = html.escape(skill["description"])
        tools_used = html.escape(skill["tools"]) if skill["tools"] else "—"
        body.append(
            "<li>"
            f'<h3><a href="{{{{BASE}}}}/artifacts/.claude/skills/{name}/SKILL.html">'
            f"<code>{html.escape(name)}</code></a></h3>"
            f"<p>{summary}</p>"
            f'<p class="card-files">Tools: {tools_used} · '
            f'<a href="{{{{BASE}}}}/artifacts/.claude/skills/{name}/SKILL.html">read</a> · '
            f'<a href="{RAW_BASE}/artifacts/.claude/skills/{name}/SKILL.md" download>'
            "download</a></p>"
            "</li>")
    body.append("</ul>\n")

    body.append("\n## Shared references\n")
    body.append(
        "Two files the mapping skills read. They are identical wherever they "
        "appear, so they are listed once here rather than repeated per skill. "
        "<code>refresh-feature-model-infos</code> is what keeps every copy in "
        "sync with the model.\n")

    ref_rows = []
    for filename, description in (
            ("feature-model-dimensions.md",
             "The feature model's dimensions, as the skills consume them"),
            ("analysis-template.md",
             "The blank analysis document each mapping fills in")):
        # Any copy will do -- they are byte-identical. Pick the first skill
        # that carries one so the link never depends on a specific skill.
        holder = next((d for d in SKILL_ORDER
                       if (ARTIFACTS / ".claude" / "skills" / d / "references"
                           / filename).is_file()), "")
        if not holder:
            continue
        url = ("{{BASE}}/artifacts/.claude/skills/"
               f"{holder}/references/{filename}")
        size = human_size((ARTIFACTS / ".claude" / "skills" / holder /
                           "references" / filename).stat().st_size)
        ref_rows.append((f'<a href="{url}" download><code>{filename}</code></a>',
                         description, size))
    if ref_rows:
        body.append(table(["File", "What it is", "Size"], ref_rows,
                          extra_class="downloads"))

    write_page("skills.md",
               {"layout": "default", "title": "Skills",
                "nav_title": "Skills", "nav_order": 5,
                "permalink": "/skills/"},
               "\n".join(body))
    return len(skills)


def render_evaluation_index(assets: Artifacts) -> None:
    """Tab 5 landing page: what the evaluation is, and how to read it."""
    body = [
        "# Evaluation\n",
        "Each tool below was mapped onto the feature model, and every mapping "
        "here is the output of the "
        f'<a href="{{{{BASE}}}}/skills/">mapping skills</a> — not a hand-made '
        "assessment. The tools are grouped by the paper they were drawn from.\n",

        "\n## What each tool page shows\n",
        "<dl class=\"provenance\">"
        "<dt>Automated mapping</dt>"
        "<dd>What <code>codebase-map</code> or <code>docs-map</code> produced "
        "from the tool's own code or documentation, unedited.</dd>"
        "<dt>Revised mapping</dt>"
        "<dd>The same mapping after the authors re-checked the cited evidence "
        "and corrected it. Both are published so the corrections are visible.</dd>"
        "<dt>Proposed model extension</dt>"
        "<dd>Where a tool had a feature the model lacked, that feature was added "
        "to a copy of the model. These are the authors' proposals, <b>not</b> "
        "skill output, and only three tools produced one.</dd>"
        "</dl>\n",

        "\n## Colour legend\n",
        colour_legend(),

        "\n## Tools\n",
    ]

    rows = []
    for paper in PAPERS:
        for tool in TOOLS:
            if TOOL_META[tool]["source"] != paper["key"]:
                continue
            href = ("{{BASE}}/evaluation/" + paper["slug"] + "/"
                    + tool.lower() + "/")
            rows.append((
                f'<a href="{href}"><b>{html.escape(TOOL_LABEL[tool])}</b></a>',
                html.escape(paper["label"]),
                f'<code>{TOOL_META[tool]["skill"]}</code>',
            ))
    body.append(table(["Tool", "Source paper", "Mapped with"], rows))

    if EXCLUDED_TOOLS:
        body.append("\n## Tools that could not be mapped\n")
        body.append(
            "These appear in the source papers but have no public codebase or "
            "documentation to map against.\n")
        body.append(table(
            ["Tool", "Source paper", "Reason"],
            [(html.escape(n), html.escape(s), html.escape(r))
             for n, s, r in EXCLUDED_TOOLS]))

    write_page("evaluation/index.md",
               {"layout": "default", "title": "Evaluation",
                "nav_title": "Evaluation", "nav_order": 6,
                "permalink": "/evaluation/"},
               sub_nav() + "\n".join(body))


def render_paper_page(paper: Dict[str, str], assets: Artifacts) -> None:
    """One page per source paper: which tools it contributed."""
    key, slug = paper["key"], paper["slug"]
    tools = [t for t in TOOLS if TOOL_META[t]["source"] == key]

    inventory = parse_paper_inventory(key)

    body = [
        f"# {html.escape(paper['label'])}\n",
        f"<p class=\"meta-line\">{html.escape(paper['venue'])}</p>\n",
        f"The tools this paper contributed to the evaluation. "
        + (f"All <b>{len(tools)}</b> of them were mapped."
           if len(tools) > 1 else
           "It contributes a single tool.") + "\n",
    ]

    rows = []
    for tool in tools:
        href = "{{BASE}}/evaluation/" + slug + "/" + tool.lower() + "/"
        entry = inventory.get(tool.lower(), {})
        rows.append((
            f'<a href="{href}"><b>{html.escape(TOOL_LABEL[tool])}</b></a>',
            html.escape(entry.get("venue", "—")),
            entry.get("availability", "—"),
            f'<code>{TOOL_META[tool]["skill"]}</code>',
        ))
    # Tools this paper lists that were not mappable.
    for name, source, reason in EXCLUDED_TOOLS:
        if source != key:
            continue
        rows.append((html.escape(name),
                     html.escape(inventory.get(name.lower(), {}).get("venue", "—")),
                     "—",
                     f"<i>not mapped — {html.escape(reason.lower())}</i>"))
    body.append(table(["Tool", "Venue", "Availability", "Mapped with"], rows))

    if paper["union"]:
        body.append(
            f"\nA merged profile combining all {len(tools)} of them is on the "
            f'<a href="{{{{BASE}}}}/evaluation/{slug}/all/">'
            f"All {html.escape(paper['label'])} tools</a> page.\n")

    write_page(f"evaluation/{slug}/index.md",
               {"layout": "default", "title": paper["label"],
                "permalink": f"/evaluation/{slug}/"},
               sub_nav(active_paper=key) + "\n".join(body))


def parse_paper_inventory(key: str) -> Dict[str, Dict[str, str]]:
    """Read the tool table out of ``evaluation/papers/<key>.md``.

    That directory is excluded from the built site because every link in it
    points at a third-party PDF, so the venue and availability columns are
    lifted here and re-rendered instead.
    """
    path = ARTIFACTS / "evaluation" / "papers" / f"{key}.md"
    if not path.is_file():
        return {}

    out: Dict[str, Dict[str, str]] = {}
    for line in read(path).splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4 or cells[0].lower() in ("tool", ""):
            continue
        if set(cells[0]) <= set("-: "):      # the header underline
            continue
        # Availability is a markdown link or plain text; keep any link, since
        # it points at the tool's own repository rather than into papers/.
        availability = re.sub(
            r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', cells[3])
        out[cells[0].lower()] = {"venue": cells[2], "availability": availability}
    return out


def render_eval_tool_page(tool: str, assets: Artifacts) -> None:
    """One page per tool: the mapping images, then the downloads."""
    key = TOOL_META[tool]["source"]
    paper = next(p for p in PAPERS if p["key"] == key)
    label = TOOL_LABEL[tool]
    shots = tool_images(tool, assets)

    body = [
        f"# {html.escape(label)}\n",
        f'<p class="meta-line">Mapped with '
        f'<code>{TOOL_META[tool]["skill"]}</code> · '
        f'from <a href="{{{{BASE}}}}/evaluation/{paper["slug"]}/">'
        f'{html.escape(paper["label"])}</a> · '
        f'<a href="{TOOL_META[tool]["repo"]}">tool repository</a></p>\n',
    ]
    body += mapping_figures(shots, label)

    entries: List[Tuple[str, str]] = []
    for rel, description in (
            (f"analyses/{tool}-analysis.md",
             "The full analysis, every finding citing its evidence"),
            (f"analyses/{tool}-readme.md",
             "How the tool was obtained and run")):
        if rel in assets:
            entries.append((rel, description))
    entries += profile_downloads(assets, tool)
    body.append(downloads_block(assets, entries))

    # The extended model is the authors' proposal, so it gets its own section
    # rather than sitting among the skill's output above.
    extended_xml = f"models/{tool}_feature_model.xml"
    if extended_xml in assets or "extended" in shots:
        body.append("\n## Proposed model extension\n")
        body.append(
            f"{html.escape(label)} exposed features the model did not have. "
            "They were added to a copy of the model, shown below. This is a "
            "proposal by the authors, not skill output.\n")
        if "extended" in shots:
            body.append(figure(
                f"The model extended with {html.escape(label)}'s features.",
                [shots["extended"]]))
        if extended_xml in assets:
            body.append(downloads_block(
                assets,
                [(extended_xml, "The extended feature model (FeatureIDE XML)")],
                heading=""))

    write_page(f"evaluation/{paper['slug']}/{tool.lower()}.md",
               {"layout": "default", "title": label,
                "permalink": f"/evaluation/{paper['slug']}/{tool.lower()}/"},
               sub_nav(active_paper=key, active_tool=tool) + "\n".join(body))


def render_union_page(key: str, assets: Artifacts) -> None:
    """A merged mapping: what a set of tools covers together.

    ``all-tools`` sits at the top of the Evaluation strip; ``wang`` sits under
    its paper. The third merged profile, mono2micro+Micro2Micro, has no page of
    its own -- it is offered as a download here, since a two-tool subset is a
    detail of the paper rather than a section of the appendix.
    """
    entry = next(m for m in MERGED if m[0] == key)
    _, prefix, label = entry

    if key == "all-tools":
        slug, active_paper, covered = "evaluation/all-tools", "", TOOLS
        permalink = "/evaluation/all-tools/"
        intro = ("Every one of the seven mapped tools, merged into a single "
                 "profile: what the tools cover <i>together</i>, and — more to "
                 "the point — what none of them covers.")
    else:
        paper = next(p for p in PAPERS if p["union"] == key)
        slug = f"evaluation/{paper['slug']}/all"
        permalink = f"/evaluation/{paper['slug']}/all/"
        active_paper = paper["key"]
        covered = [t for t in TOOLS if TOOL_META[t]["source"] == paper["key"]]
        intro = (f"The {len(covered)} tools from {html.escape(paper['label'])}, "
                 "merged into a single profile.")

    shots = collect_images(assets, [
        ("claude", f"{prefix}_claudeMapping.png", "Automated mapping"),
        ("revised", f"{prefix}_revisedMapping.png", "Revised mapping"),
        ("extended", f"{prefix}_extended.png", "Extended model"),
        ("extendedMapping", f"{prefix}_extendedMapping.png", "Extended model"),
    ], label)
    # all-tools names its extended image _extended.png; every other family uses
    # _extendedMapping.png. Normalise so the page does not care.
    if "extended" not in shots and "extendedMapping" in shots:
        shots["extended"] = shots.pop("extendedMapping")
    shots.pop("extendedMapping", None)

    body = [
        f"# {html.escape(label)}\n",
        f"<p>{intro}</p>\n",
        "<p>Merged with <code>merge-profiles</code> from the individual "
        "mappings of "
        + ", ".join(
            f'<a href="{{{{BASE}}}}/evaluation/'
            f'{next(p["slug"] for p in PAPERS if p["key"] == TOOL_META[t]["source"])}'
            f'/{t.lower()}/">{html.escape(TOOL_LABEL[t])}</a>'
            for t in covered)
        + ".</p>\n",
    ]
    body += mapping_figures(shots, label)

    entries = profile_downloads(assets, key)
    body.append(downloads_block(assets, entries))

    extended_xml = f"models/{key}_feature_model.xml"
    if extended_xml in assets or "extended" in shots:
        body.append("\n## Proposed model extension\n")
        body.append(
            "The union of every feature the tools exposed that the model did "
            "not have, added to a copy of the model. A proposal by the authors, "
            "not skill output.\n")
        if "extended" in shots:
            body.append(figure("The model extended with the union of the "
                               "tools' extra features.", [shots["extended"]]))
        if extended_xml in assets:
            body.append(downloads_block(
                assets,
                [(extended_xml, "The extended feature model (FeatureIDE XML)")],
                heading=""))

    if key == "all-tools":
        subset = "mono2micro+Micro2Micro"
        rows = profile_downloads(
            assets, subset, "mono2micro_user_review+Micro2Micro_user_review")
        if rows:
            body.append("\n## Other merged mappings\n")
            body.append(
                "The paper also discusses Mono2Micro and Micro2Micro together, "
                "as the two tools that share a lineage. That pairing has its own "
                "merged profile.\n")
            body.append(downloads_block(assets, rows, heading=""))

    write_page(f"{slug}.md",
               {"layout": "default", "title": label, "permalink": permalink},
               sub_nav(active_paper=active_paper, active_tool=key)
               + "\n".join(body))


def tally_profiles() -> Dict[str, Dict[str, Dict[str, int]]]:
    """Per-mapping colour counts, for the cross-check main() prints.

    The site no longer renders a coverage page, but these counts are what the
    paper's mapping-summary table reports, so they stay worth printing on every
    build: a silent change here means the paper and the artifacts have drifted.
    """
    profiles_dir = ARTIFACTS / "feature_model" / ".profiles"
    out: Dict[str, Dict[str, Dict[str, int]]] = {}

    def add(name: str, auto_path: Path, review_path: Path) -> None:
        if not auto_path.is_file():
            return
        entry = {"auto": colour_counts(parse_profile(auto_path))}
        if review_path.is_file():
            entry["review"] = colour_counts(parse_profile(review_path))
        out[name] = entry

    for tool in TOOLS:
        add(tool, profiles_dir / f"{tool}.profile",
            profiles_dir / f"{tool}_user_review.profile")
    for key, _prefix, _label in MERGED:
        review = ("mono2micro_user_review+Micro2Micro_user_review"
                  if key == "mono2micro+Micro2Micro" else f"{key}_user_review")
        add(key, profiles_dir / f"{key}.profile",
            profiles_dir / f"{review}.profile")
    return out


# --------------------------------------------------------------------------
# Post-processing
# --------------------------------------------------------------------------

def prune_pages() -> None:
    """Delete previously generated pages so renames cannot leave orphans.

    Generated pages are identified by their banner, so the hand-written
    ``pages/index.md`` is never touched. Matching the "GENERATED by" prefix
    rather than the full banner keeps this working across renames of this
    script.
    """
    if not PAGES.is_dir():
        return
    for path in sorted(PAGES.rglob("*.md")):
        if BANNER_MARK in path.read_text(encoding="utf-8"):
            path.unlink()


def apply_baseurl() -> None:
    """Replace the {{BASE}} placeholder with a Liquid relative_url call.

    Writing ``{{ '/x' | relative_url }}`` directly through the generator would
    collide with the Liquid-escaping in strip_frontmatter_hazards, so pages use
    a placeholder and it is substituted here, last.

    Scoped to ``pages/`` so it can never rewrite anything under ``artifacts/``,
    whose markdown is the archived source of truth and must stay pristine. The
    explicit guard below documents that invariant.
    """
    for path in PAGES.rglob("*.md"):
        if ARTIFACTS in path.parents:
            continue
        text = path.read_text(encoding="utf-8")
        if "{{BASE}}" not in text:
            continue
        text = re.sub(r"\{\{BASE\}\}(/[^\s\"')<>]*)",
                      lambda m: "{{ '" + m.group(1) + "' | relative_url }}", text)
        path.write_text(text, encoding="utf-8")


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

def main() -> int:
    if not ARTIFACTS.is_dir():
        print(f"error: {ARTIFACTS} not found — run from the repository root",
              file=sys.stderr)
        return 2

    try:
        assets = Artifacts()
        summary = register_artifacts(assets)

        prune_pages()

        render_feature_model(assets)
        render_initial_model(assets)
        studies = render_meta_review(assets)
        skills = render_skills(assets)

        render_evaluation_index(assets)
        render_union_page("all-tools", assets)
        for paper in PAPERS:
            render_paper_page(paper, assets)
            if paper["union"]:
                render_union_page(paper["union"], assets)
        for tool in TOOLS:
            render_eval_tool_page(tool, assets)

        counts = tally_profiles()

        apply_baseurl()
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"{len(TOOLS)} tools, {summary['profiles']} profiles, "
          f"{summary['images']} images, {studies} studies, {skills} skills")
    print(f"extended models: {', '.join(summary['extended_models']) or 'none'}")

    print("\nper-tool colour counts (automated / reviewed) — "
          "cross-check against the paper's mapping summary table:")
    header = "  {:<24}".format("tool") + "".join(f"{COLOUR_SHORT[c][:11]:>13}" for c in COLOURS)
    print(header)
    for key, value in counts.items():
        auto = value["auto"]
        review = value.get("review")
        cells = "".join(
            "{:>13}".format(f"{auto[c]}" + (f" ({review[c]})" if review else ""))
            for c in COLOURS)
        print(f"  {key:<24}{cells}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
