false
Version analysis=Yellow
Entity=Yellow
Dynamic analysis=Yellow
Inheritance=Yellow
Merge of clusters=Yellow
MoJoFM=Red
Runtime=Yellow
Analytical=Light_Green
Development=Light_Green
Expert knowledge=Magenta
K-means++=Yellow
API endpoint=Yellow
Business process model=Yellow
Directly in the code=Yellow
Relations=Magenta
Method=Light_Green
Functional=Light_Green
Use case=Yellow
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Light_Green
Lexical=Yellow
Sequence of accesses=Light_Green
Granularity refinement=Magenta
By task=Yellow
Visualization=Magenta
Cohesion=Light_Green
Microservices Decomposition and Refactoring=Magenta
Team size=Yellow
Elements=Magenta
Microservices=Light_Green
Association=Light_Green
Digital format=Yellow
Static analysis=Light_Green
Evolution=Yellow
Database schema=Light_Green
Coupling=Light_Green
Structure=Light_Green
Asynchronization=Yellow
Refactoring=Light_Green
Elements size=Magenta
Quality Assessment=Magenta
Source code=Light_Green
Splitting of clusters=Yellow
Transfer of elements between clusters=Yellow
Type=Dark_Green
Algorithms=Light_Green
Frequency=Magenta
Representation Collection=Light_Green
Graphical Comparison=Yellow
Manual Editing=Yellow
Task=Yellow
Cluster view=Yellow
Inter Structure=Light_Green
Hierarchical clustering=Yellow
Model analysis=Yellow
Data flow=Magenta
Complexity=Yellow
Aggregation Criteria=Light_Green
Metrics=Magenta
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Light_Green
Behavior=Light_Green
Functionality Refactoring=Magenta
Control flow=Magenta
Several Decompositions=Red
Monolith=Light_Green
User interactions=Yellow
Documentation=Yellow
Color=Yellow
Community detection=Light_Green
Single Decomposition=Magenta
Representation=Light_Green
Memory level=Yellow
Structural relationship=Magenta
Sizes=Yellow
Functionality=Yellow
External=Yellow
Class=Light_Green
Runtime log traces=Yellow
Paper document=Yellow
Contributor=Yellow
Granularity view=Magenta
Granularity=Light_Green
Source=Light_Green
Services Refactoring=Light_Green
Genetic algorithms=Yellow
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Yellow
Higher-Level Models=Yellow
Inner structure=Yellow
By contributor=Yellow
Call graph=Light_Green
Distance between elements=Yellow
Compare metrics=Magenta
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
