false
Version analysis=Yellow
Entity=Yellow
Dynamic analysis=Light_Green
Inheritance=Yellow
Merge of clusters=Yellow
MoJoFM=Red
Runtime=Light_Green
Analytical=Light_Green
Development=Light_Green
Expert knowledge=Yellow
K-means++=Yellow
API endpoint=Yellow
Business process model=Yellow
Directly in the code=Yellow
Relations=Red
Method=Light_Green
Functional=Yellow
Use case=Yellow
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Light_Green
Lexical=Light_Green
Sequence of accesses=Yellow
Granularity refinement=Yellow
By task=Yellow
Visualization=Yellow
Cohesion=Yellow
Microservices Decomposition and Refactoring=Red
Team size=Yellow
Elements=Red
Microservices=Light_Green
Association=Light_Green
Digital format=Yellow
Static analysis=Light_Green
Evolution=Yellow
Database schema=Yellow
Coupling=Yellow
Structure=Light_Green
Asynchronization=Yellow
Refactoring=Light_Green
Elements size=Red
Quality Assessment=Red
Source code=Light_Green
Splitting of clusters=Yellow
Transfer of elements between clusters=Yellow
Type=Dark_Green
Algorithms=Light_Green
Frequency=Yellow
Representation Collection=Light_Green
Graphical Comparison=Yellow
Manual Editing=Yellow
Task=Yellow
Cluster view=Yellow
Inter Structure=Light_Green
Hierarchical clustering=Light_Green
Model analysis=Yellow
Data flow=Yellow
Complexity=Yellow
Aggregation Criteria=Light_Green
Metrics=Red
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Light_Green
Behavior=Light_Green
Functionality Refactoring=Yellow
Control flow=Yellow
Several Decompositions=Red
Monolith=Light_Green
User interactions=Yellow
Documentation=Yellow
Color=Yellow
Community detection=Yellow
Single Decomposition=Red
Representation=Light_Green
Memory level=Yellow
Structural relationship=Yellow
Sizes=Yellow
Functionality=Yellow
External=Yellow
Class=Light_Green
Runtime log traces=Light_Green
Paper document=Yellow
Contributor=Yellow
Granularity view=Red
Granularity=Light_Green
Source=Light_Green
Services Refactoring=Light_Green
Genetic algorithms=Yellow
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Yellow
Higher-Level Models=Yellow
Inner structure=Yellow
By contributor=Yellow
Call graph=Light_Green
Distance between elements=Yellow
Compare metrics=Yellow
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
