false
Version analysis=Light_Green
Entity=Yellow
Dynamic analysis=Yellow
Inheritance=Yellow
Merge of clusters=Yellow
MoJoFM=Red
Runtime=Yellow
Analytical=Light_Green
Development=Light_Green
Expert knowledge=Yellow
K-means++=Yellow
API endpoint=Yellow
Business process model=Yellow
Directly in the code=Yellow
Relations=Light_Green
Method=Yellow
Functional=Yellow
Use case=Yellow
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Orange
Lexical=Orange
Sequence of accesses=Yellow
Granularity refinement=Yellow
By task=Light_Green
Visualization=Light_Green
Cohesion=Magenta
Microservices Decomposition and Refactoring=Orange
Team size=Light_Green
Elements=Dark_Green
Microservices=Light_Green
Association=Yellow
Digital format=Yellow
Static analysis=Light_Green
Evolution=Light_Green
Database schema=Yellow
Coupling=Magenta
Structure=Yellow
Asynchronization=Yellow
Refactoring=Orange
Elements size=Light_Green
Quality Assessment=Light_Green
Source code=Light_Green
Splitting of clusters=Yellow
Transfer of elements between clusters=Yellow
Type=Dark_Green
Algorithms=Light_Green
Frequency=Yellow
Representation Collection=Light_Green
Graphical Comparison=Light_Green
Manual Editing=Yellow
Task=Light_Green
Cluster view=Light_Green
Inter Structure=Yellow
Hierarchical clustering=Magenta
Model analysis=Yellow
Data flow=Yellow
Complexity=Yellow
Aggregation Criteria=Orange
Metrics=Light_Green
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Yellow
Behavior=Yellow
Functionality Refactoring=Yellow
Control flow=Yellow
Several Decompositions=Red
Monolith=Light_Green
User interactions=Yellow
Documentation=Yellow
Color=Magenta
Community detection=Yellow
Single Decomposition=Dark_Green
Representation=Light_Green
Memory level=Yellow
Structural relationship=Light_Green
Sizes=Yellow
Functionality=Yellow
External=Yellow
Class=Light_Green
Runtime log traces=Yellow
Paper document=Yellow
Contributor=Light_Green
Granularity view=Light_Green
Granularity=Light_Green
Source=Light_Green
Services Refactoring=Light_Green
Genetic algorithms=Yellow
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Light_Green
Higher-Level Models=Yellow
Inner structure=Yellow
By contributor=Light_Green
Call graph=Yellow
Distance between elements=Yellow
Compare metrics=Yellow
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
