false
Version analysis=Light_Green
Entity=Yellow
Dynamic analysis=Yellow
Inheritance=Yellow
Merge of clusters=Yellow
MoJoFM=Light_Green
Runtime=Yellow
Analytical=Light_Green
Development=Light_Green
Expert knowledge=Light_Green
K-means++=Yellow
API endpoint=Yellow
Business process model=Yellow
Directly in the code=Yellow
Relations=Light_Green
Method=Yellow
Functional=Yellow
Use case=Yellow
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Light_Green
Lexical=Light_Green
Sequence of accesses=Yellow
Granularity refinement=Yellow
By task=Light_Green
Visualization=Light_Green
Cohesion=Light_Green
Microservices Decomposition and Refactoring=Light_Green
Team size=Yellow
Elements=Dark_Green
Microservices=Light_Green
Association=Light_Green
Digital format=Yellow
Static analysis=Yellow
Evolution=Light_Green
Database schema=Yellow
Coupling=Light_Green
Structure=Light_Green
Asynchronization=Yellow
Refactoring=Light_Green
Elements size=Red
Quality Assessment=Light_Green
Source code=Light_Green
Splitting of clusters=Yellow
Transfer of elements between clusters=Yellow
Type=Light_Green
Algorithms=Light_Green
Frequency=Yellow
Representation Collection=Light_Green
Graphical Comparison=Yellow
Manual Editing=Yellow
Task=Light_Green
Cluster view=Light_Green
Inter Structure=Light_Green
Hierarchical clustering=Yellow
Model analysis=Yellow
Data flow=Yellow
Complexity=Yellow
Aggregation Criteria=Light_Green
Metrics=Light_Green
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Light_Green
Behavior=Light_Green
Functionality Refactoring=Yellow
Control flow=Yellow
Several Decompositions=Dark_Green
Monolith=Yellow
User interactions=Yellow
Documentation=Yellow
Color=Yellow
Community detection=Yellow
Single Decomposition=Yellow
Representation=Light_Green
Memory level=Yellow
Structural relationship=Light_Green
Sizes=Yellow
Functionality=Yellow
External=Light_Green
Class=Light_Green
Runtime log traces=Yellow
Paper document=Yellow
Contributor=Yellow
Granularity view=Light_Green
Granularity=Light_Green
Source=Light_Green
Services Refactoring=Light_Green
Genetic algorithms=Light_Green
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Light_Green
Higher-Level Models=Yellow
Inner structure=Yellow
By contributor=Yellow
Call graph=Light_Green
Distance between elements=Yellow
Compare metrics=Light_Green
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
