false
Version analysis=Yellow
Entity=Yellow
Dynamic analysis=Light_Green
Inheritance=Light_Green
Merge of clusters=Magenta
MoJoFM=Red
Runtime=Light_Green
Analytical=Light_Green
Development=Light_Green
Expert knowledge=Light_Green
K-means++=Yellow
API endpoint=Yellow
Business process model=Magenta
Directly in the code=Magenta
Relations=Light_Green
Method=Yellow
Functional=Light_Green
Use case=Light_Green
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Light_Green
Lexical=Yellow
Sequence of accesses=Light_Green
Granularity refinement=Yellow
By task=Yellow
Visualization=Light_Green
Cohesion=Light_Green
Microservices Decomposition and Refactoring=Light_Green
Team size=Yellow
Elements=Dark_Green
Microservices=Light_Green
Association=Light_Green
Digital format=Yellow
Static analysis=Light_Green
Evolution=Yellow
Database schema=Yellow
Coupling=Light_Green
Structure=Light_Green
Asynchronization=Yellow
Refactoring=Light_Green
Elements size=Light_Green
Quality Assessment=Light_Green
Source code=Light_Green
Splitting of clusters=Magenta
Transfer of elements between clusters=Light_Green
Type=Dark_Green
Algorithms=Light_Green
Frequency=Magenta
Representation Collection=Light_Green
Graphical Comparison=Light_Green
Manual Editing=Light_Green
Task=Yellow
Cluster view=Light_Green
Inter Structure=Light_Green
Hierarchical clustering=Light_Green
Model analysis=Magenta
Data flow=Yellow
Complexity=Yellow
Aggregation Criteria=Light_Green
Metrics=Light_Green
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Light_Green
Behavior=Light_Green
Functionality Refactoring=Yellow
Control flow=Light_Green
Several Decompositions=Red
Monolith=Light_Green
User interactions=Magenta
Documentation=Light_Green
Color=Light_Green
Community detection=Yellow
Single Decomposition=Dark_Green
Representation=Light_Green
Memory level=Yellow
Structural relationship=Light_Green
Sizes=Yellow
Functionality=Yellow
External=Yellow
Class=Light_Green
Runtime log traces=Light_Green
Paper document=Yellow
Contributor=Yellow
Granularity view=Light_Green
Granularity=Light_Green
Source=Light_Green
Services Refactoring=Light_Green
Genetic algorithms=Yellow
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Yellow
Higher-Level Models=Light_Green
Inner structure=Light_Green
By contributor=Yellow
Call graph=Light_Green
Distance between elements=Yellow
Compare metrics=Magenta
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
