false
Version analysis=Yellow
Entity=Light_Green
Dynamic analysis=Yellow
Inheritance=Light_Green
Merge of clusters=Yellow
MoJoFM=Red
Runtime=Yellow
Analytical=Light_Green
Development=Light_Green
Expert knowledge=Light_Green
K-means++=Yellow
API endpoint=Yellow
Business process model=Yellow
Directly in the code=Yellow
Relations=Dark_Green
Method=Light_Green
Functional=Light_Green
Use case=Yellow
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Light_Green
Lexical=Yellow
Sequence of accesses=Yellow
Granularity refinement=Yellow
By task=Yellow
Visualization=Dark_Green
Cohesion=Light_Green
Microservices Decomposition and Refactoring=Light_Green
Team size=Yellow
Elements=Dark_Green
Microservices=Light_Green
Association=Light_Green
Digital format=Yellow
Static analysis=Light_Green
Evolution=Yellow
Database schema=Yellow
Coupling=Light_Green
Asynchronization=Yellow
Structure=Dark_Green
Refactoring=Light_Green
Elements size=Light_Green
Quality Assessment=Light_Green
Source code=Light_Green
Splitting of clusters=Yellow
Transfer of elements between clusters=Light_Green
Type=Dark_Green
Algorithms=Light_Green
Frequency=Yellow
Representation Collection=Light_Green
Graphical Comparison=Light_Green
Manual Editing=Light_Green
Task=Yellow
Cluster view=Light_Green
Inter Structure=Dark_Green
Hierarchical clustering=Yellow
Model analysis=Yellow
Data flow=Light_Green
Complexity=Yellow
Aggregation Criteria=Light_Green
Metrics=Light_Green
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Light_Green
Behavior=Light_Green
Functionality Refactoring=Yellow
Control flow=Light_Green
Several Decompositions=Yellow
Monolith=Light_Green
User interactions=Yellow
Documentation=Yellow
Color=Light_Green
Community detection=Light_Green
Single Decomposition=Light_Green
Representation=Light_Green
Memory level=Yellow
Structural relationship=Light_Green
Sizes=Yellow
Functionality=Yellow
External=Yellow
Class=Yellow
Runtime log traces=Yellow
Paper document=Yellow
Contributor=Yellow
Granularity view=Light_Green
Granularity=Light_Green
Source=Light_Green
Genetic algorithms=Yellow
Services Refactoring=Light_Green
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Yellow
Higher-Level Models=Yellow
Inner structure=Light_Green
By contributor=Yellow
Call graph=Light_Green
Distance between elements=Yellow
Compare metrics=Light_Green
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
