false
Version analysis=Light_Green
Entity=Light_Green
Dynamic analysis=Light_Green
Inheritance=Light_Green
Merge of clusters=Yellow
MoJoFM=Red
Runtime=Light_Green
Analytical=Light_Green
Development=Dark_Green
Expert knowledge=Light_Green
K-means++=Yellow
API endpoint=Yellow
Business process model=Yellow
Directly in the code=Yellow
Relations=Dark_Green
Method=Light_Green
Functional=Light_Green
Use case=Light_Green
Hungarian algorithm=Yellow
Response time=Yellow
Package=Yellow
Domain Knowledge=Dark_Green
Lexical=Light_Green
Sequence of accesses=Light_Green
Granularity refinement=Yellow
By task=Light_Green
Visualization=Dark_Green
Cohesion=Light_Green
Microservices Decomposition and Refactoring=Light_Green
Team size=Light_Green
Elements=Dark_Green
Microservices=Light_Green
Association=Light_Green
Digital format=Yellow
Static analysis=Light_Green
Evolution=Dark_Green
Database schema=Light_Green
Coupling=Light_Green
Asynchronization=Yellow
Structure=Dark_Green
Refactoring=Light_Green
Elements size=Light_Green
Quality Assessment=Light_Green
Source code=Light_Green
Splitting of clusters=Yellow
Transfer of elements between clusters=Light_Green
Type=Dark_Green
Algorithms=Light_Green
Frequency=Light_Green
Representation Collection=Light_Green
Graphical Comparison=Light_Green
Manual Editing=Light_Green
Task=Light_Green
Cluster view=Light_Green
Inter Structure=Dark_Green
Hierarchical clustering=Light_Green
Model analysis=Yellow
Data flow=Light_Green
Complexity=Yellow
Aggregation Criteria=Dark_Green
Metrics=Light_Green
Data flow diagram=Yellow
CPU level=Yellow
Adjacency=Light_Green
Behavior=Light_Green
Functionality Refactoring=Yellow
Control flow=Light_Green
Several Decompositions=Yellow
Monolith=Light_Green
User interactions=Yellow
Documentation=Yellow
Color=Light_Green
Community detection=Light_Green
Single Decomposition=Light_Green
Representation=Light_Green
Memory level=Yellow
Structural relationship=Light_Green
Sizes=Yellow
Functionality=Yellow
External=Yellow
Class=Light_Green
Runtime log traces=Light_Green
Paper document=Yellow
Contributor=Light_Green
Granularity view=Light_Green
Granularity=Light_Green
Source=Light_Green
Genetic algorithms=Yellow
Services Refactoring=Light_Green
Formal concept analysis=Yellow
Collection Technique=Light_Green
Collector=Light_Green
Version history=Light_Green
Higher-Level Models=Light_Green
Inner structure=Light_Green
By contributor=Light_Green
Call graph=Light_Green
Distance between elements=Yellow
Compare metrics=Light_Green
featureColorMeaning0=Leaf/Group: absent or broken (mandatory)
featureColorMeaning1=Constraint violation
featureColorMeaning2=Leaf/Group: absent (optional)
featureColorMeaning3=Group: fully satisfied
featureColorMeaning4=Leaf: exists / Group: partially satisfied
featureColorMeaning5=Extra Feature
featureColorMeaning6=InvalidColor (unused in FeatureIDE)
featureColorMeaning7=InvalidColor (unused in FeatureIDE)
featureColorMeaning8=Leaf: unclear / indirect evidence
featureColorMeaning9=InvalidColor (unused in FeatureIDE)
