"""The tables that vary when a tool, paper, skill or colour is added.

Almost everything configurable about the site lives here, so adding or renaming
a tool is an edit to this file rather than to any logic. Nothing here imports
from the rest of the package, and nothing here computes: these are declarations.

The wording in SKILL_SUMMARY and MAPPING_BLURB is reader-facing prose that ends
up on the published pages -- edit it here, never in pages/.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

#: The whole-folder downloads offered on the Feature Model and Initial Model
#: pages.
BUNDLE_NAME = "feature_model.zip"
INITIAL_BUNDLE_NAME = "initial_feature_model.zip"

#: Per-skill downloads, offered on each skill's own page: the skill folder
#: itself, and the artifacts that skill produced.
SKILL_BUNDLE = "{skill}-skill.zip"
SKILL_OUTPUT_BUNDLE = "{skill}-outputs.zip"

#: Marks a generated page. It names ``generate.py`` because that is the command
#: a reader runs, even though the writing is done from this package.
#: ``prune_pages`` matches on the "GENERATED by" prefix rather than the whole
#: string, so a rename cannot leave undeletable orphans behind.
BANNER = "<!-- GENERATED by generate.py — do not edit by hand. -->"
BANNER_MARK = "GENERATED by"

#: Tools in the order the paper presents them (Table "Sources and Tools
#: Selected for evaluation"), not alphabetically.
TOOLS: List[str] = [
    "mono2micro",
    "mono2micro_IBM",
    "Micro2Micro",
    "CARGO",
    "HyDec",
    "MEM",
    "MOSAIC",
]

#: Display names, since directory names are not presentable as-is.
TOOL_LABEL: Dict[str, str] = {
    "mono2micro": "Mono2Micro",
    "mono2micro_IBM": "Mono2Micro (IBM)",
    "Micro2Micro": "Micro2Micro",
    "CARGO": "CARGO",
    "HyDec": "HyDec",
    "MEM": "MEM",
    "MOSAIC": "MOSAIC",
}

#: exportedImages/ uses different casing from analyses/ for some tools.
IMAGE_PREFIX: Dict[str, str] = {
    "mono2micro": "mono2micro",
    "mono2micro_IBM": "mono2micro_IBM",
    "Micro2Micro": "micro2micro",
    "CARGO": "CARGO",
    "HyDec": "HyDec",
    "MEM": "MEM",
    "MOSAIC": "MOSAIC",
}

#: Which skill produced each mapping, and the tool's source paper.
TOOL_META: Dict[str, Dict[str, str]] = {
    "mono2micro": {
        "skill": "codebase-map",
        "source": "Lopes2023",
        "repo": "https://github.com/socialsoftware/mono2micro",
    },
    "mono2micro_IBM": {
        "skill": "docs-map",
        "source": "Wang2024",
        "repo": "https://www.ibm.com/products/mono2micro",
    },
    "Micro2Micro": {
        "skill": "codebase-map",
        "source": "Zhong2025",
        "repo": "https://github.com/wuxiaoxue/micro2micro",
    },
    "CARGO": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/konveyor/tackle-data-gravity-insights",
    },
    "HyDec": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/khaledsellami/decomp-hydec",
    },
    "MEM": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/gmazlami/microserviceExtraction-backend",
    },
    "MOSAIC": {
        "skill": "codebase-map",
        "source": "Wang2024",
        "repo": "https://github.com/mosaic-tool/mosaic",
    },
}

#: Tools the paper lists but excludes from the mapping.
EXCLUDED_TOOLS: List[Tuple[str, str, str]] = [
    ("Data-Centric", "Wang2024", "No online codebase or documentation"),
    ("Log2MS", "Wang2024", "No online codebase or documentation"),
]

#: Source papers, in the order the Evaluation sub-navigation lists them. Which
#: tools belong to each is derived from TOOL_META["source"], never duplicated
#: here. ``union`` names the merged profile covering that paper's tools, where
#: one exists -- only Wang2024 has one, since the other two papers contribute a
#: single tool each and a union of one is just the tool.
PAPERS: List[Dict[str, str]] = [
    {"key": "Lopes2023", "slug": "lopes2023", "label": "Lopes 2023",
     "venue": "MSc thesis, Instituto Superior Técnico, 2023", "union": ""},
    {"key": "Wang2024", "slug": "wang2024", "label": "Wang 2024",
     "venue": "Empirical study comparing eight tools, 2024", "union": "wang"},
    {"key": "Zhong2025", "slug": "zhong2025", "label": "Zhong 2025",
     "venue": "IEEE Transactions on Software Engineering, 2025", "union": ""},
]

#: Where the repository is browsable. SKILL.md carries a YAML header, so Jekyll
#: renders it to SKILL.html and never emits a raw .md -- the only way to offer
#: the file itself is to link the source. See the include: note in _config.yml.
RAW_BASE = ("https://raw.githubusercontent.com/socialsoftware/"
            "UnifiedFeatureModelArtifacts/main")

#: Skills in pipeline order rather than alphabetical: what runs first reads
#: first. ``refresh-feature-model-infos`` is orthogonal and comes last.
SKILL_ORDER: List[str] = [
    "extract-codebases-from-paper",
    "codebase-map",
    "docs-map",
    "verify-analysis",
    "merge-profiles",
    "refresh-feature-model-infos",
]

#: Merged profiles: site key -> (profile stem, exportedImages prefix, label).
MERGED: List[Tuple[str, str, str]] = [
    ("all-tools", "all_tools", "All tools"),
    ("wang", "wang", "Wang et al. tools"),
    ("mono2micro+Micro2Micro", "mono2micro+micro2micro", "Mono2Micro + Micro2Micro"),
]

#: Colour semantics, per the paper's Table "Meaning of colors in the mapping".
#: Order is the reporting order of Table "Summary of the mapping results".
COLOURS: List[str] = [
    "Dark_Green",
    "Light_Green",
    "Yellow",
    "Red",
    "Orange",
    "Magenta",
]

COLOUR_MEANING: Dict[str, str] = {
    "Dark_Green": "Every feature in the group was mapped to the tool "
                  "(feature groups only, never leaves)",
    "Light_Green": "The feature was mapped to the tool",
    "Yellow": "The feature was not mapped to the tool, but it is optional",
    "Red": "The feature was not mapped to the tool, although it was mandatory",
    "Orange": "The feature was not mapped to the tool and this violates a constraint",
    "Magenta": "The mapping of this feature is inconclusive (automated mapping), "
               "or the feature is present in the tool but absent from the model",
}

COLOUR_SHORT: Dict[str, str] = {
    "Dark_Green": "Group fully mapped",
    "Light_Green": "Mapped",
    "Yellow": "Unmapped (optional)",
    "Red": "Unmapped (mandatory)",
    "Orange": "Constraint violation",
    "Magenta": "Inconclusive / extra",
}


#: Reader-facing summaries of each skill. The ``description`` in SKILL.md is a
#: trigger-phrase prompt aimed at the model ("use this when the user says ...")
#: and refers to an earlier repository layout, so it does not read as prose on a
#: web page. The raw description stays available on the SKILL.md itself.
SKILL_SUMMARY: Dict[str, str] = {
    "extract-codebases-from-paper":
        "Given a paper, identifies the tools it discusses and, for each one, "
        "searches for its codebase or documentation URL. Codebases found are "
        "downloaded automatically; missing ones are recorded for a manual "
        "lookup. Particularly useful for papers that compare several tools, and "
        "it copes with broken or outdated links by falling back to a web search.",
    "codebase-map":
        "Given the codebase of a tool, maps it onto the feature model and "
        "produces three artifacts: a human-readable report, an analysis "
        "document, and a colour profile. The analysis mirrors the structure of "
        "the feature model, one bullet per leaf feature, and every finding must "
        "cite at least one <code>file:line</code> reference so the mapping can "
        "be verified independently.",
    "docs-map":
        "Mirrors <code>codebase-map</code> for tools that are not open source. "
        "It takes a documentation URL instead of a local path and cites "
        "documentation links rather than <code>file:line</code> references as "
        "evidence, producing the same three artifacts.",
    "verify-analysis":
        "Reconciles several runs of the mapping skills, which are "
        "non-deterministic and may differ in results, evidence, and conclusions. "
        "It inspects the different versions of a tool's mapping and, where they "
        "disagree, re-examines the evidence to determine the best-supported "
        "conclusion. When that is still inconclusive the feature is marked "
        "inconclusive and left for the user to decide.",
    "merge-profiles":
        "Combines the per-tool colour profiles into a union profile showing what "
        "a chosen set of tools covers together. With no arguments it merges "
        "every analysed tool; given a paper it merges only that paper's tools; "
        "given tool names it merges just those.",
    "refresh-feature-model-infos":
        "Checks whether the files that depend on the feature model are still in "
        "sync with it, reports any discrepancies, and updates them once "
        "approved.",
}

#: What each skill writes, in one line, for the "What it produced" section of
#: its page, above that section's download table. The files themselves are
#: resolved from TOOL_META and MERGED rather than listed here, so adding a tool
#: never means editing this table.
#:
#: A skill is absent when it ships no archive of its own; its page falls back to
#: SKILL_NO_BUNDLE_NOTE instead. That is the case for
#: ``refresh-feature-model-infos`` and ``verify-analysis``.
SKILL_OUTPUT_BLURB: Dict[str, str] = {
    "extract-codebases-from-paper":
        "A tool inventory per paper, listing every tool the paper covers with "
        "its venue, its availability, and a link to its analysis.",
    "codebase-map":
        "An analysis document, a run README and a colour profile for each of "
        "the tools mapped from source.",
    "docs-map":
        "The same three files as <code>codebase-map</code>, for the one tool "
        "mapped from its documentation rather than its source.",
    "merge-profiles":
        "The union profiles, each combining a chosen set of per-tool mappings.",
}

#: The "What it produced" text for a skill that ships no archive but still
#: warrants the section, to say why there is nothing to download.
#: ``verify-analysis`` is deliberately in neither this table nor
#: SKILL_OUTPUT_BLURB, so its page omits the section entirely: its product is
#: the reviewed profiles, and those are already presented with the model.
SKILL_NO_BUNDLE_NOTE: Dict[str, str] = {
    "refresh-feature-model-infos":
        "Nothing of its own. This skill edits the files that describe the "
        "feature model in place, so its output is the change itself rather "
        "than a new artifact.",
}

#: The layout the skills expect of the repository they run in. They were run
#: against an earlier working tree, so this is deliberately NOT this
#: repository's layout -- the paths inside SKILL.md (feature_model/
#: representation/.profiles/, my_paper/text.md) refer to the tree below.
#: Reproduced so a reader can rebuild it and re-run them.
SKILL_REPO_LAYOUT = """\
.
├── feature_model/
│   └── representation/
│       ├── feature_model.xml        the canonical model the skills read
│       └── .profiles/
│           └── <tool>.profile       one colour profile per tool
├── evaluation/
│   ├── analyses/
│   │   └── <tool>/
│   │       ├── analysis.md          the mapping, every finding citing evidence
│   │       └── README.md            how the tool was obtained and run
│   └── papers/
│       └── <PaperKey>.md            the tool inventory for one paper
├── papers/
│   ├── surveys/<PaperKey>.pdf       the source papers
│   └── tools/<Tool>.pdf             the per-tool papers
└── ../extracted-codebases/
    └── <tool>/                      cloned repositories, OUTSIDE the repo\
"""


#: One line per downloadable mapping, for the Colour profiles table. Keyed by
#: tool name and by MERGED key. TOOL_META carries only provenance (skill,
#: source, repo), so there is nowhere else to say what a tool actually does;
#: this mirrors SKILL_SUMMARY above. The merged entries say what the union
#: means, since a reader meets "wang" here as a filename and nothing else.
MAPPING_BLURB: Dict[str, str] = {
    "mono2micro": "Identifies microservices in a monolith from the codebase "
                  "and its execution traces. The tool the initial model was "
                  "derived from.",
    "mono2micro_IBM": "IBM's commercial offering of the same name, mapped from "
                      "its documentation rather than its source.",
    "Micro2Micro": "Refactors an existing microservice architecture rather "
                   "than splitting a monolith, moving functionality between "
                   "services.",
    "CARGO": "Partitions a monolith using a graph of its code and data "
             "dependencies, with the database kept in view.",
    "HyDec": "Decomposes a monolith with a hybrid of static and dynamic "
             "analysis.",
    "MEM": "Derives candidate microservices from version-control history, "
           "grouping code that tends to change together.",
    "MOSAIC": "Identifies microservices from a combination of structural and "
              "semantic signals in the codebase.",
    "all-tools": "Every one of the seven mapped tools merged into one profile: "
                 "what they cover together, and what none of them covers.",
    "wang": "The tools evaluated in Wang 2024, merged into one profile.",
    "mono2micro+Micro2Micro": "The two tools that share a lineage, merged into "
                              "one profile. Discussed in the paper as a pair; "
                              "it has no page of its own.",
}
