"""The two passes that run around page rendering.

``prune_pages`` clears out previously generated pages before anything is
written; ``apply_baseurl`` resolves the ``{{BASE}}`` placeholder afterwards.
Both are scoped to ``pages/`` so they can never touch ``artifacts/``, which is
the archived source of truth and must stay pristine.
"""

from __future__ import annotations

import re

from .config import BANNER_MARK
from .paths import ARTIFACTS, PAGES


def prune_pages() -> None:
    """Delete previously generated pages so renames cannot leave orphans.

    Generated pages are identified by their banner, so the hand-written
    ``pages/index.md`` is never touched. Matching the "GENERATED by" prefix
    rather than the full banner keeps this working across renames of this
    script.
    """
    if not PAGES.is_dir():
        return
    for path in sorted(PAGES.rglob("*.md")):
        if BANNER_MARK in path.read_text(encoding="utf-8"):
            path.unlink()


def apply_baseurl() -> None:
    """Replace the {{BASE}} placeholder with a Liquid relative_url call.

    Writing ``{{ '/x' | relative_url }}`` directly through the generator would
    collide with the escaping done while pages are assembled, so pages carry a
    placeholder and it is substituted here, last.

    Scoped to ``pages/`` so it can never rewrite anything under ``artifacts/``,
    whose markdown is the archived source of truth and must stay pristine. The
    explicit guard below documents that invariant.
    """
    for path in PAGES.rglob("*.md"):
        if ARTIFACTS in path.parents:
            continue
        text = path.read_text(encoding="utf-8")
        if "{{BASE}}" not in text:
            continue
        text = re.sub(r"\{\{BASE\}\}(/[^\s\"')<>]*)",
                      lambda m: "{{ '" + m.group(1) + "' | relative_url }}", text)
        path.write_text(text, encoding="utf-8")
